const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../app.js'),'utf8');
const context=vm.createContext({console,window:{},document:{getElementById:()=>null}});
vm.runInContext(source.split('const decisionList=')[0],context);
vm.runInContext(`
  let renders=0,saves=0;
  render=()=>renders++;queueQuickSave=()=>saves++;
  const first={id:'G1',code:'AAA',description:'Original',radius:200,items:[{id:'S1'}]};
  const second={id:'G2',code:'BBB',description:'Other',radius:100,items:[]};
  state.groups=[first,second];
`,context);
const run=code=>vm.runInContext(code,context);
assert.match(run('groupNameHistoryControls(first)'),/data-name-undo[^>]*disabled/);
run(`const codeInput={};recordGroupNameEdit(first,codeInput,'code','A');first.code='A';recordGroupNameEdit(first,codeInput,'code','NEWCODE');first.code='NEWCODE';`);
assert.equal(run('groupNameHistory(first).undo.length'),1,'typing is a single undo step');
run(`recordGroupNameEdit(first,{},'description','New name');first.description='New name';restoreGroupName('G1','undo');`);
assert.equal(run('first.description'),'Original');assert.equal(run('first.code'),'NEWCODE');
run(`restoreGroupName('G1','undo');`);assert.equal(run('first.code'),'AAA');
assert.equal(run('first.radius'),200);assert.equal(run('first.items[0].id'),'S1');assert.equal(run('second.code'),'BBB');
run(`restoreGroupName('G1','redo');restoreGroupName('G1','redo');`);
assert.equal(run('first.code'),'NEWCODE');assert.equal(run('first.description'),'New name');
run(`restoreGroupName('G1','undo');recordGroupNameEdit(first,{},'description','Replacement');first.description='Replacement';restoreGroupName('G1','redo');`);
assert.equal(run('first.description'),'Replacement');assert.equal(run('groupNameHistory(first).redo.length'),0);
run(`const unchanged={};recordGroupNameEdit(second,unchanged,'code','BBB');`);
assert.equal(run('groupNameHistory(second).undo.length'),0);
assert.equal(run(`groupNameHistory({id:'G1',code:'AAA',description:'Fresh'}).undo.length`),0,'regenerated groups have fresh history');
assert.equal(run('renders'),5);assert.equal(run('saves'),5);
run(`for(let i=0;i<110;i++){recordGroupNameEdit(second,{},'code','CODE'+i);second.code='CODE'+i;}`);
assert.equal(run('groupNameHistory(second).undo.length'),100);
run(`
  refreshGroupErrorSummary=()=>{};
  const input={value:'LASTCODE',classList:{toggle(){}},setCustomValidity(){},nextElementSibling:{}};
  window.renameGroupCode('G1',input);
`);
assert.equal(run('first.code'),'LASTCODE');
run(`window.undoGroupName('G1');`);assert.equal(run('first.code'),'NEWCODE');
run(`input.value='Last description';window.renameGroupDescription('G1',input);window.undoGroupName('G1');`);
assert.equal(run('first.description'),'Replacement');
run(`window.redoGroupName('G1');`);assert.equal(run('first.description'),'Last description');
const cardSource=source.slice(source.indexOf('function groupCard('),source.indexOf('function decisionPlaceMap('));
assert.ok(!cardSource.includes('proposal-list'));assert.ok(!cardSource.includes('proposals=state.groups'));
assert.ok(cardSource.includes('groupNameHistoryControls(group)'));
assert.ok(cardSource.includes('renameGroupCode('));assert.ok(cardSource.includes('renameGroupDescription('));assert.ok(cardSource.includes('reassignStop('));
const shell=fs.readFileSync(path.join(__dirname,'../app-shell.js'),'utf8');
assert.ok(shell.includes("'Annuler':'Undo'"));assert.ok(shell.includes("'Rétablir':'Redo'"));
console.log('PASS: per-place name undo/redo, grouped typing, independent places, redo branching, fresh groups, bounded history, bilingual controls and preserved stop assignments.');
