const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {createPortalClient}=require('../portal.js');
const config={url:'https://testproject.supabase.co',publishableKey:'sb_publishable_TEST_ONLY',bucket:'gtfs-private'};
(async()=>{
  const calls=[],queue=[];
  const client=createPortalClient(config,async(url,options)=>{calls.push({url,options});const next=queue.shift();assert.ok(next,'Unexpected request');return new Response(next.body===undefined?'null':JSON.stringify(next.body),{status:next.status||200});});
  await assert.rejects(client.files(),/SIGN_IN_REQUIRED/);assert.equal(calls.length,0);
  queue.push({body:{access_token:'synthetic-session',user:{email:'reader@example.test'}}});await client.login('reader@example.test','synthetic-password');
  assert.ok(!calls[0].options.headers.Authorization,'Publishable keys are not JWTs');
  assert.equal(calls[0].options.credentials,'omit');assert.equal(calls[0].options.cache,'no-store');
  queue.push({body:'viewer'});assert.equal(await client.role(),'viewer');assert.equal(calls.at(-1).options.headers.Authorization,'Bearer synthetic-session');
  queue.push({status:403});await assert.rejects(client.allow('unauthorized@example.test',true),error=>error.status===403,'Server permission errors are not hidden');
  queue.push({body:Array.from({length:100},(_,i)=>({name:'file-'+i,id:i+1}))},{body:[{name:'last',id:101}]});assert.equal((await client.files()).length,101);
  queue.push({body:'bytes'});await client.download('../a?b#c.html');assert.ok(calls.at(-1).url.endsWith('..%2Fa%3Fb%23c.html'));
  assert.ok(calls.at(-1).url.includes('/object/authenticated/gtfs-private/'));
  queue.push({status:401});await assert.rejects(client.role(),error=>error.status===401);await assert.rejects(client.files(),/SIGN_IN_REQUIRED/);
  queue.push({body:{access_token:'ignored-signup-token'}});await client.signup('new@example.test','synthetic-pass','https://example.test/portal.html');await assert.rejects(client.files(),/SIGN_IN_REQUIRED/,'Signup never becomes an authenticated session');
  queue.push({body:{access_token:'recovery-token'}},{body:{}},{body:{}});await client.reset('reader@example.test','123456','new-synthetic-password');await assert.rejects(client.files(),/SIGN_IN_REQUIRED/);
  assert.equal(JSON.parse(calls.at(-3).options.body).type,'recovery');
  assert.throws(()=>createPortalClient({...config,publishableKey:'sb_secret_NEVER_ALLOWED'}));
  assert.throws(()=>createPortalClient({...config,url:'https://attacker.test'}));
  const root=path.resolve(__dirname,'..'),sql=fs.readFileSync(path.join(root,'supabase/001_private_portal.sql'),'utf8'),js=fs.readFileSync(path.join(root,'portal.js'),'utf8');
  assert.ok(sql.includes('u.id = auth.uid()')&&sql.includes('u.email_confirmed_at is not null'));
  assert.ok(!sql.replace(/--[^\n]*/g,'').includes('user_metadata'));
  for(const op of ['select','insert','update','delete'])assert.ok(sql.includes('as restrictive for '+op));
  assert.ok(sql.includes("values('gtfs-private','gtfs-private',false"));
  assert.ok(sql.includes('set search_path = \'\''));
  assert.ok(sql.includes("public.gtfs_portal_role() is distinct from 'admin'"));
  assert.ok(!js.includes('sessionStorage')&&!js.includes('localStorage.setItem(\'token'));
  console.log('PASS: private portal client contracts, session expiry, no persisted tokens, recovery, request encoding, pagination and SQL security structure (not a live RLS verification).');
})().catch(error=>{console.error(error);process.exitCode=1;});
