const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const context=vm.createContext({Date});
const source=fs.readFileSync('report-editor.js','utf8');vm.runInContext(source,context);
const data={places:[{key:'a',code:'AAA',description:'First'},{key:'b',code:'BBB',description:'Second'},{key:'c',code:'CCC',description:'Third'}],assignments:{s1:'a',s2:'b'},points:[{id:'s1',label:'001',description:'First physical stop'},{id:'s2',description:'Second physical stop'}]};
const edits={places:data.places.map(p=>({...p})),assignments:{...data.assignments}};
const review=context.reportReviewModel(data,edits);
assert.equal(review.summary()[0].stops[0].description,'First physical stop');
assert.equal(review.summary()[0].stops[0].id,'s1');
assert.equal(review.summary()[0].stops[0].label,'001');
assert.equal(review.summary()[2].stops.length,0);
review.set('a',true);review.set('b',true);review.set('c',true);
assert.equal(review.summary().filter(p=>p.validated).length,3);
assert.equal(review.reconcile(),false);
edits.places[0].description='Changed';assert.equal(review.reconcile(),true);assert.equal(review.approved('a'),false);assert.equal(review.approved('b'),true);
review.set('a',true);edits.assignments.s1='b';review.reconcile();
assert.equal(review.summary()[0].stops.length,0,'transferred stops leave the source summary');
assert.equal(review.summary()[1].stops.length,2,'current assignments, not the initial grouping, populate the summary');
assert.equal(review.approved('a'),false,'source must be re-reviewed');assert.equal(review.approved('b'),false,'target must be re-reviewed');assert.equal(review.approved('c'),true);
edits.assignments.s1='a';review.reconcile();assert.equal(review.approved('a'),false,'undo must not silently restore approval');
review.set('a',true);edits.places[0].code='NEW';review.reconcile();assert.equal(review.approved('a'),false);
review.set('b',true);const saved=JSON.parse(JSON.stringify({...data,edits}));
const reopened=context.reportReviewModel(saved,saved.edits);assert.equal(reopened.reconcile(),false);assert.equal(reopened.approved('b'),true);assert.ok(reopened.summary().find(p=>p.key==='b').validatedAt);
assert.equal(reopened.summary()[0].stops[0].description,'First physical stop','saved summary retains stop descriptions');
reopened.set('b',false);assert.equal(reopened.approved('b'),false);
assert.equal(reopened.set('unknown',true),false);
saved.clientReview.approvals.ghost={signature:'stale'};assert.equal(reopened.reconcile(),true);assert.equal(reopened.approved('ghost'),false);
assert.ok(source.includes('reviewer?.cleanClone(clone)'));assert.ok(source.includes('placeApprovals}'));
assert.ok(source.includes("clone.querySelectorAll('[data-review-runtime]')"));
const app=fs.readFileSync('app.js','utf8');assert.ok(app.includes('${reportReviewModel.toString()}'));assert.ok(app.includes('${mountReportReview.toString()}'));
assert.ok(source.includes('button.onclick=()=>approve(id,!model.approved(id))'),'normal cards use the shared approval handler');
assert.ok(source.includes("onchange=event=>approve(key,event.target.checked)"),'review uses the same approval handler');
assert.ok(!source.includes('Windowed review'),'ordinary report is the only windowed mode');
assert.ok(!source.includes('start(from,false)'),'inspecting another place must not enter a separate windowed review');
assert.ok(source.includes('revealPlace(id)'),'normal comparison navigates to the ordinary card');
assert.ok(source.includes("button.setAttribute('aria-pressed',String(approved))"),'card approval status is synchronized on refresh');
assert.ok(source.includes('scroll-margin-top:var(--report-anchor-offset,70px)'),'place anchors clear the measured sticky module menu');
assert.ok(source.includes('--place-table-height'),'long lists use the remaining visible area');
console.log('PASS: independent approvals, source/target invalidation, no implicit reapproval on undo, saved HTML state, unknown places and embedded review runtime.');
