const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),ctx=vm.createContext({TextEncoder});
for(const f of ['report-package.js','report-network.js','report-timetable-export.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),ctx);
const template=fs.readFileSync(path.join(root,'tmp/report-editor-network.html'),'utf8');
const data=JSON.parse(template.match(/<script id="report-data" type="application\/json">([\s\S]*?)<\/script>/)[1]);
data.gtfs.archiveEntries.find(f=>f.name==='calendar_dates.txt').text+='\nspecial,20261004,1';
data.networkView={date:'2026-10-04',direction:'both',route:'r1',timing:true};
const tools=ctx.reportTimetableExportTools(),zip=ctx.reportPackageTools().zip;
const edits={places:[{key:data.places[0].key,code:'CLEAN',description:'Harbour & Central'}],assignments:{}};
const model=tools.build(data,edits,data.networkView);
assert.equal(model.compact,true);
assert.equal(tools.build(data,edits,{date:'2026-10-04',route:'r1'}).direction,'both');
assert.equal(tools.build(data,edits,{...data.networkView,compact:false}).compact,false);
assert.deepEqual(Array.from(model.blocks,b=>b.direction),['0','1']);
assert.equal(model.blocks[0].rows.length,2);assert.equal(model.blocks[1].rows.length,1);
assert.equal(model.blocks[0].rows[1].headway,1800);assert.equal(model.blocks[1].rows[0].headway,null);
assert.match(model.blocks[0].stops[0],/CLEAN · Harbour & Central/);
assert.equal(model.frequencies.length,1);
assert.equal(tools.build(data,edits,{...data.networkView,direction:'1'}).blocks.length,1);
assert.equal(tools.build(data,edits,{...data.networkView,date:'2026-10-06'}).blocks.length,0);
assert.throws(()=>tools.build(data,edits,{...data.networkView,date:'bad'}));
for(const name of ['../x','/x','a//x','a/./x','a/../x','C:/x','a\\x'])assert.throws(()=>zip([{name,text:'a'}],{allowPaths:true}));
assert.throws(()=>zip([{name:'xl/workbook.xml',text:'a'}]));
for(const language of ['fr','en']){
  const localized={...model,language};
  const html=tools.printHtml(localized);
  assert.ok(!html.includes('<iframe'));assert.ok(!html.includes('https://'));
  assert.match(html,/A4 landscape/);assert.match(html,/Harbour &amp; Central/);
  assert.match(html,/30 min/);assert.ok(html.includes(language==='en'?'Both directions':'Les deux directions'));
  fs.writeFileSync(path.join(root,'tmp','report-editor-timetables-'+language+'.html'),html);
  fs.writeFileSync(path.join(root,'tmp','report-editor-timetables-'+language+'.xlsx'),tools.xlsx(localized));
}
const longBlock={...model.blocks[0],stops:Array.from({length:14},(_,i)=>'TP '+i),rows:[{id:'=NOT_A_FORMULA()',times:Array.from({length:14},(_,i)=>90000+i*60),headway:null}]};
const longModel={...model,blocks:[longBlock],frequencies:[]};
assert.equal((tools.printHtml({...longModel,compact:false}).match(/class="print-page"/g)||[]).length,3);
const compactHtml=tools.printHtml(longModel);
assert.equal((compactHtml.match(/class="print-page condensed-route"/g)||[]).length,3);
assert.equal((compactHtml.match(/class="compact-pattern"/g)||[]).length,3);
assert.equal((compactHtml.match(/class="vertical-stop"/g)||[]).length,14);
assert.match(compactHtml,/25:13:00/);
const multiPattern={...model,frequencies:[],blocks:[...model.blocks,{...longBlock,pattern:3}]};
const multiHtml=tools.printHtml(multiPattern);
assert.equal((multiHtml.match(/class="print-page condensed-route"/g)||[]).length,4);
assert.match(multiHtml,/Direction 0/);assert.match(multiHtml,/Direction 1/);
assert.match(multiHtml,/Pattern 3/);assert.match(multiHtml,/30 min/);
const longTrips={...model,frequencies:[],blocks:[{...longBlock,rows:Array.from({length:19},(_,i)=>({id:'trip-long-'+i,headway:i?300:null,times:Array.from({length:14},(_,j)=>90000+i*300+j*60)}))},model.blocks[1]]};
const longTripsHtml=tools.printHtml(longTrips);
assert.equal((longTripsHtml.match(/class="print-page condensed-route"/g)||[]).length,9);
for(let i=0;i<19;i++)assert.equal((longTripsHtml.match(new RegExp('>trip-long-'+i+'<','g'))||[]).length,3);
assert.match(longTripsHtml,/Points 11–14 \/ 14 · Trips 17–19 \/ 19/);
assert.match(tools.printHtml({...model,blocks:[model.blocks[1]],frequencies:[]}),/margin-left:50%/);
assert.match(tools.printHtml({...model,blocks:[{...model.blocks[0],direction:'?'}],frequencies:[]}),/Direction \?/);
fs.writeFileSync(path.join(root,'tmp/report-editor-timetables-compact-wide.html'),multiHtml);
assert.match(tools.printHtml(longModel),/25:00:00/);
fs.writeFileSync(path.join(root,'tmp/report-editor-timetables-wide.xlsx'),tools.xlsx(longModel));
fs.writeFileSync(path.join(root,'tmp/report-editor-both.html'),template.replace(/(<script id="report-data" type="application\/json">)[\s\S]*?(<\/script>)/,(_,a,b)=>a+JSON.stringify(data).replaceAll('<','\\u003c')+b));
console.log('PASS: both directions, independent headways, filters, live labels, FR/EN exports, wide print tables, safe OOXML paths.');
