const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),fields={},statuses=[],saved=[];
const context=vm.createContext({console,document:{getElementById:id=>fields[id]??={}},window:{},clearTimeout(){},setTimeout,Date});
vm.runInContext(fs.readFileSync(path.join(root,'app.js'),'utf8').split('const decisionList=')[0],context);
vm.runInContext(`
  updateWorkspaceOpenButton=()=>{};refreshWorkspaceChoices=async()=>{};
  loadWorkingStopsFromDirectory=async()=>{};
  restoreWorkspaceSnapshot=snapshot=>{state.parsed=snapshot.parsed;};
`,context);
context.workspaceStatus=(...args)=>statuses.push(args);
context.saveWorkspaceRecord=async record=>saved.push(record);
const snapshot={savedAt:'2026-10-07T15:04:05Z',parsed:{agency:{rows:[{agency_name:'Métrobus / St. John’s'}]},stops:{rows:[]},times:{rows:[]}}};
const reset=()=>{vm.runInContext(`state.parsed={};state.workspace={mode:'none'};`,context);statuses.length=0;saved.length=0;};
(async()=>{
  const name=context.workspaceSaveName(snapshot);
  assert.match(name,/^GTFS_HASTUS_Metrobus_St_John_s_20261007_\d{6}\.json$/);
  assert.ok(name.endsWith(context.workspaceTimestamp(snapshot.savedAt)+'.json'));
  assert.match(context.workspaceSaveName({savedAt:snapshot.savedAt}),/^GTFS_HASTUS_Client_/);
  const browser={id:'browser-latest',type:'browser',snapshot},directory={id:'disk',name:'Disk',type:'directory',handle:{name:'Disk'},savedAt:'2026-10-06T12:00:00Z',lastOpened:'2026-10-09T12:00:00Z'};
  context.workspaceRecords=async()=>[directory,browser,{id:'empty',type:'directory',savedAt:null,lastOpened:'2026-10-10T12:00:00Z'}];
  await context.restoreLatestWorkspace();
  assert.equal(vm.runInContext('state.workspace.mode',context),'browser');
  assert.equal(vm.runInContext('state.workspace.filename',context),name);
  assert.equal(saved.length,0,'Restoring a browser save must not rewrite it');
  reset();let prompted=0;
  directory.savedAt='2026-10-08T12:00:00Z';directory.handle={name:'Disk',queryPermission:async()=> 'prompt',requestPermission:async()=>{prompted++;return 'granted';}};
  await context.restoreLatestWorkspace();
  assert.equal(prompted,0);assert.equal(vm.runInContext('state.workspace.mode',context),'none');
  assert.equal(fields['workspace-choice'].value,'recent:disk');assert.match(statuses.at(-1)[2],/Cliquez sur Ouvrir/);
  reset();directory.handle.queryPermission=async()=> 'granted';
  context.readNamedWorkspace=async()=>({snapshot,filename:name});
  await context.restoreLatestWorkspace();
  assert.equal(vm.runInContext('state.workspace.mode',context),'directory');assert.equal(saved[0].savedAt,snapshot.savedAt);
  assert.equal(prompted,0);
  reset();let allowed=true;
  context.readNamedWorkspace=async()=>{allowed=false;return {snapshot,filename:name};};
  await context.restoreLatestWorkspace(()=>allowed);
  assert.equal(vm.runInContext('state.workspace.mode',context),'none','Pending startup must not overwrite a new user action');
  reset();context.readNamedWorkspace=async()=>{throw new Error('Missing file');};
  await context.restoreLatestWorkspace();assert.equal(statuses.at(-1)[0],'error');assert.equal(saved.length,0);
  reset();context.workspaceRecords=async()=>[];await context.restoreLatestWorkspace();assert.equal(statuses.length,0);
  console.log('PASS: latest save restored, agency/date/time names, empty folders ignored, no permission prompt, interrupted startup and missing file safe');
})().catch(error=>{console.error(error);process.exitCode=1;});
