const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync('index.html','utf8'),fields=new Map();
const field=id=>{if(!fields.has(id))fields.set(id,{value:'',textContent:'',classList:{toggle(k,v){this[k]=v;},add(k){this[k]=true;},remove(k){this[k]=false;}}});return fields.get(id);};
const document={getElementById:field,querySelectorAll:()=>[],body:{setAttribute(k,v){this[k]=v;},classList:{remove(){},toggle(){}}}};
const ctx=vm.createContext({document,console,window:{}});
vm.runInContext(fs.readFileSync('app.js','utf8').split('const decisionList=')[0],ctx);
vm.runInContext('queueQuickSave=()=>{};setupMapping=()=>{};render=()=>{};',ctx);
assert.deepEqual([...html.matchAll(/data-mode="([^"]+)"/g)].map(m=>m[1]),['geographic','network','timetables','scheduling','reports']);
assert.ok(html.indexOf('id="mode-section"')<html.indexOf('id="feed-section"'));
assert.ok(html.indexOf('id="reports-workflow"')<html.indexOf('id="place-report-panel"'));
assert.ok(!html.includes('id="working-timetable-mode"'));
vm.runInContext("state.geographicReady=true;state.groups=[{code:'KEPT'}];state.decisions=[{id:'001',choice:'KEEP'}];",ctx);
ctx.setMode('network');assert.equal(document.body['data-workflow'],'network');assert.equal(field('network-module').classList.hidden,false);assert.equal(field('scheduling-unit-module').classList.hidden,true);
ctx.setMode('scheduling');assert.equal(field('network-module').classList.hidden,true);assert.equal(field('scheduling-unit-module').classList.hidden,false);
ctx.setMode('reports');assert.equal(document.body['data-workflow'],'reports');assert.equal(vm.runInContext('state.mode',ctx),'geographic');assert.equal(vm.runInContext('state.groups[0].code',ctx),'KEPT');assert.equal(vm.runInContext('state.decisions[0].choice',ctx),'KEEP');
assert.equal(field('reports-workflow').classList.hidden,false);
ctx.setMode('geographic');assert.equal(field('reports-workflow').classList.hidden,true);
ctx.setMode('maps');assert.equal(document.body['data-workflow'],'network','legacy route-map mode uses the unified workflow');
vm.runInContext('state.workingParentStations=2;',ctx);ctx.setMode('workingTimetables');assert.equal(document.body['data-workflow'],'network');assert.equal(field('network-stop-source').value,'working');
ctx.setMode('geographic');assert.equal(vm.runInContext('state.groups[0].code',ctx),'KEPT');
ctx.DayRouteSummary={placeLabels:()=>({})};ctx.agencyClientIdentity=()=>({name:'Fixture'});
field('network-language').value='en';field('network-stop-source').value='working';
vm.runInContext("state.parsed={stops:{headers:['stop_id'],rows:[{stop_id:'old'}]},times:{headers:['stop_id'],rows:[{stop_id:'old'}]},routes:{headers:[],rows:[]},trips:{headers:[],rows:[]}};state.workingStops={headers:['stop_id'],rows:[{stop_id:'new',parent_station:'PLACE'},{stop_id:'PLACE',location_type:'1',stop_name:'Prepared place'}]};state.stopIdRemap=new Map([['old','new']]);",ctx);
const network=ctx.standaloneNetworkData();assert.equal(network.gtfs.stops.rows[0].stop_id,'new');assert.equal(network.gtfs.times.rows[0].stop_id,'new');assert.equal(network.places[0].code,'PLACE');
assert.equal(vm.runInContext('state.parsed.times.rows[0].stop_id',ctx),'old','working view must not modify source schedules');
field('network-stop-source').value='gtfs';assert.equal(ctx.standaloneNetworkData().gtfs.stops.rows[0].stop_id,'old');
console.log('PASS: five workflows, legacy mode migration, separate panel visibility, working source and geographic decisions preserved across navigation.');
